/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_RUNNINGLIGHTSCONFIG_PB_H_INCLUDED
#define PB_RUNNINGLIGHTSCONFIG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Color {
    uint32_t R;
    uint32_t G;
    uint32_t B;
/* @@protoc_insertion_point(struct:Color) */
} Color;


typedef struct _RunningLightsConfig {
    pb_size_t which_Settings;
    union {
        Color color;
        uint32_t delay;
    } Settings;
/* @@protoc_insertion_point(struct:RunningLightsConfig) */
} RunningLightsConfig;


/* Initializer values for message structs */
#define RunningLightsConfig_init_default         {0, {Color_init_default}}
#define Color_init_default                       {0, 0, 0}
#define RunningLightsConfig_init_zero            {0, {Color_init_zero}}
#define Color_init_zero                          {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Color_R_tag                              1
#define Color_G_tag                              2
#define Color_B_tag                              3
#define RunningLightsConfig_color_tag            1
#define RunningLightsConfig_delay_tag            2

/* Struct field encoding specification for nanopb */
#define RunningLightsConfig_FIELDLIST(X, a) \
X(a, STATIC, ONEOF, MESSAGE, (Settings,color,Settings.color), 1) \
X(a, STATIC, ONEOF, UINT32, (Settings,delay,Settings.delay), 2)
#define RunningLightsConfig_CALLBACK NULL
#define RunningLightsConfig_DEFAULT NULL
#define RunningLightsConfig_Settings_color_MSGTYPE Color

#define Color_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, UINT32, R, 1) \
X(a, STATIC, SINGULAR, UINT32, G, 2) \
X(a, STATIC, SINGULAR, UINT32, B, 3)
#define Color_CALLBACK NULL
#define Color_DEFAULT NULL

extern const pb_msgdesc_t RunningLightsConfig_msg;
extern const pb_msgdesc_t Color_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define RunningLightsConfig_fields &RunningLightsConfig_msg
#define Color_fields &Color_msg

/* Maximum encoded size of messages (where known) */
#define RunningLightsConfig_size                 20
#define Color_size                               18

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
