/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev */

#include "data.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(com_example_nk_tripleled_util_Data, com_example_nk_tripleled_util_Data, AUTO)


PB_BIND(com_example_nk_tripleled_util_Data_Color, com_example_nk_tripleled_util_Data_Color, AUTO)



/* @@protoc_insertion_point(eof) */
