/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.0-dev */

#ifndef PB_COM_EXAMPLE_NK_TRIPLELED_UTIL_DATA_PB_H_INCLUDED
#define PB_COM_EXAMPLE_NK_TRIPLELED_UTIL_DATA_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _com_example_nk_tripleled_util_Data_Color {
    int32_t R;
    int32_t G;
    int32_t B;
/* @@protoc_insertion_point(struct:com_example_nk_tripleled_util_Data_Color) */
} com_example_nk_tripleled_util_Data_Color;


typedef struct _com_example_nk_tripleled_util_Data {
    int32_t mode;
    com_example_nk_tripleled_util_Data_Color color;
/* @@protoc_insertion_point(struct:com_example_nk_tripleled_util_Data) */
} com_example_nk_tripleled_util_Data;


/* Initializer values for message structs */
#define com_example_nk_tripleled_util_Data_init_default {0, com_example_nk_tripleled_util_Data_Color_init_default}
#define com_example_nk_tripleled_util_Data_Color_init_default {0, 0, 0}
#define com_example_nk_tripleled_util_Data_init_zero {0, com_example_nk_tripleled_util_Data_Color_init_zero}
#define com_example_nk_tripleled_util_Data_Color_init_zero {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define com_example_nk_tripleled_util_Data_Color_R_tag 1
#define com_example_nk_tripleled_util_Data_Color_G_tag 2
#define com_example_nk_tripleled_util_Data_Color_B_tag 3
#define com_example_nk_tripleled_util_Data_mode_tag 1
#define com_example_nk_tripleled_util_Data_color_tag 2

/* Struct field encoding specification for nanopb */
#define com_example_nk_tripleled_util_Data_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, INT32, mode, 1) \
X(a, STATIC, SINGULAR, MESSAGE, color, 2)
#define com_example_nk_tripleled_util_Data_CALLBACK NULL
#define com_example_nk_tripleled_util_Data_DEFAULT NULL
#define com_example_nk_tripleled_util_Data_color_MSGTYPE com_example_nk_tripleled_util_Data_Color

#define com_example_nk_tripleled_util_Data_Color_FIELDLIST(X, a) \
X(a, STATIC, SINGULAR, INT32, R, 1) \
X(a, STATIC, SINGULAR, INT32, G, 2) \
X(a, STATIC, SINGULAR, INT32, B, 3)
#define com_example_nk_tripleled_util_Data_Color_CALLBACK NULL
#define com_example_nk_tripleled_util_Data_Color_DEFAULT NULL

extern const pb_msgdesc_t com_example_nk_tripleled_util_Data_msg;
extern const pb_msgdesc_t com_example_nk_tripleled_util_Data_Color_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define com_example_nk_tripleled_util_Data_fields &com_example_nk_tripleled_util_Data_msg
#define com_example_nk_tripleled_util_Data_Color_fields &com_example_nk_tripleled_util_Data_Color_msg

/* Maximum encoded size of messages (where known) */
#define com_example_nk_tripleled_util_Data_size  46
#define com_example_nk_tripleled_util_Data_Color_size 33

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
